name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  buildv41:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: IDF Build
        uses: docker://espressif/idf:v4.1
        with:
          args: idf.py build

  buildv42:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: IDF Build
        uses: docker://espressif/idf:v4.2
        with:
          args: idf.py build
